
/* This file was generated by idltool 53.6. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYMUSIC_H
#include <libraries/kittyMusic.h>
#endif

extern ULONG                VARARGS68K _kittymusic_Obtain(struct kittyMusicIFace *);
extern ULONG                VARARGS68K _kittymusic_Release(struct kittyMusicIFace *);
extern char *               VARARGS68K _kittymusic_makeLookupTable(struct kittyMusicIFace *);
extern void                 VARARGS68K _kittymusic_FreeLookupTable(struct kittyMusicIFace *, void * table);
extern void *               VARARGS68K _kittymusic_makeContext(struct kittyMusicIFace *);
extern void                 VARARGS68K _kittymusic_FreeContext(struct kittyMusicIFace *, void * table);
