#ifndef KITTYMUSIC_INTERFACE_DEF_H
#define KITTYMUSIC_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYMUSIC_H
#include <libraries/kittyMusic.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct kittyMusicIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct kittyMusicIFace *Self);
	ULONG APICALL (*Release)(struct kittyMusicIFace *Self);
	void APICALL (*Expunge)(struct kittyMusicIFace *Self);
	struct Interface * APICALL (*Clone)(struct kittyMusicIFace *Self);
	char * APICALL (*makeLookupTable)(struct kittyMusicIFace *Self);
	void APICALL (*FreeLookupTable)(struct kittyMusicIFace *Self, void * table);
	void * APICALL (*makeContext)(struct kittyMusicIFace *Self);
	void APICALL (*FreeContext)(struct kittyMusicIFace *Self, void * table);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* KITTYMUSIC_INTERFACE_DEF_H */
