
/* This file was generated by idltool 53.6. Do not edit */

#include "kittyMusic_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _kittymusic_Obtain,
    _kittymusic_Release,
    NULL,
    NULL,
    _kittymusic_makeLookupTable,
    _kittymusic_FreeLookupTable,
    _kittymusic_makeContext,
    _kittymusic_FreeContext,
    (APTR)-1
};

