#ifndef INLINE4_KITTYMUSIC_H
#define INLINE4_KITTYMUSIC_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYMUSIC_H
#include <libraries/kittyMusic.h>
#endif
#include <interfaces/kittyMusic.h>

/* Inline macros for Interface "main" */
#define makeLookupTable() IkittyMusic->makeLookupTable() 
#define FreeLookupTable(table) IkittyMusic->FreeLookupTable((table)) 
#define makeContext() IkittyMusic->makeContext() 
#define FreeContext(table) IkittyMusic->FreeContext((table)) 

#endif /* INLINE4_KITTYMUSIC_H */
